default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS_DB") { 100 } %>
  reaping_frequency: <%= ENV.fetch("FREQUENCY_CONNECTIONS_CHECK") { 100 } %>
  host: <%= ENV.fetch('POSTGRESQL_HOST', '') %>
  password: <%= ENV.fetch('POSTGRESQL_PASSWORD', '') %>
  username: <%= ENV.fetch('POSTGRESQL_USERNAME', '') %>
development:
  <<: *default
  database: buffet_development
test:
  <<: *default
  database: buffet_test

production:
  <<: *default
  database: <%= ENV.fetch('POSTGRESQL_DBNAME', 'buffet_production') %>
